2024-04-28 22:57:52,686 INFO    StreamThr :10207 [internal.py:wandb_internal():86] W&B internal server running at pid: 10207, started at: 2024-04-28 22:57:52.685278
2024-04-28 22:57:52,688 DEBUG   HandlerThread:10207 [handler.py:handle_request():146] handle_request: status
2024-04-28 22:57:52,693 INFO    WriterThread:10207 [datastore.py:open_for_write():87] open: /Users/sarahburbank/Desktop/iw/pdb_analysis/ftr/ml_analysis/wandb/run-20240428_225752-x4n3ga70/run-x4n3ga70.wandb
2024-04-28 22:57:52,693 DEBUG   SenderThread:10207 [sender.py:send():379] send: header
2024-04-28 22:57:52,694 DEBUG   SenderThread:10207 [sender.py:send():379] send: run
2024-04-28 22:57:52,828 ERROR   SenderThread:10207 [internal_api.py:execute():373] 400 response executing GraphQL.
2024-04-28 22:57:52,828 ERROR   SenderThread:10207 [internal_api.py:execute():374] {"errors":[{"message":"you may not log runs directly to your organization, please try using your team entity","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-04-28 22:57:52,828 ERROR   SenderThread:10207 [sender.py:send_run():971] you may not log runs directly to your organization, please try using your team entity (Error 400: Bad Request)
Traceback (most recent call last):
  File "/Users/sarahburbank/Desktop/iw/pdb_analysis/ftr/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/Users/sarahburbank/Desktop/iw/pdb_analysis/ftr/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2217, in upsert_run
    response = self.gql(
  File "/Users/sarahburbank/Desktop/iw/pdb_analysis/ftr/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/Users/sarahburbank/Desktop/iw/pdb_analysis/ftr/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/sarahburbank/Desktop/iw/pdb_analysis/ftr/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/sarahburbank/Desktop/iw/pdb_analysis/ftr/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/sarahburbank/Desktop/iw/pdb_analysis/ftr/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/sarahburbank/Desktop/iw/pdb_analysis/ftr/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/Users/sarahburbank/Desktop/iw/pdb_analysis/ftr/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sarahburbank/Desktop/iw/pdb_analysis/ftr/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 969, in send_run
    server_run = self._init_run(run, config_value_dict)
  File "/Users/sarahburbank/Desktop/iw/pdb_analysis/ftr/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 1014, in _init_run
    server_run, inserted, server_messages = self._api.upsert_run(
  File "/Users/sarahburbank/Desktop/iw/pdb_analysis/ftr/lib/python3.10/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: you may not log runs directly to your organization, please try using your team entity (Error 400: Bad Request)
2024-04-28 22:57:52,986 DEBUG   HandlerThread:10207 [handler.py:handle_request():146] handle_request: shutdown
2024-04-28 22:57:52,987 INFO    HandlerThread:10207 [handler.py:finish():866] shutting down handler
2024-04-28 22:57:53,699 INFO    WriterThread:10207 [datastore.py:close():296] close: /Users/sarahburbank/Desktop/iw/pdb_analysis/ftr/ml_analysis/wandb/run-20240428_225752-x4n3ga70/run-x4n3ga70.wandb
2024-04-28 22:57:53,832 INFO    SenderThread:10207 [sender.py:finish():1546] shutting down sender
